### ISSUE TITLE
PgHero

### ISSUE THREAD

**Issue by g-ones** [VanessaDockers/pgsteroids#9]
Смотрел вопросы к вебинару, там Паша порекомендовал PgHero

https://github.com/bmorton/pghero_solo - @allustin ты про него забыл.

Надо прикрутить. Только там образ дурацкий - ruby 2.3.0, придется перепиливать на ruby-alpine

**Comment by allustin** [comment]
Блин... Завтра прикручу @g-ones - Windows пользователям давать ?

**Comment by allustin** [comment]
Добавлен в релиз - отсутствующие индексы он конечно показывает очень странно. Видимо они там попривыкли к простым запросам в Web ;-)
